/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyIcon1 {
        /**
          * The icon name
         */
        "name": string;
        /**
          * The icon size
         */
        "size": string;
    }
    interface MyIcon2 {
        /**
          * The icon name
         */
        "name": string;
        /**
          * The icon size
         */
        "size": string;
    }
    interface MyIcon3 {
        /**
          * The icon name
         */
        "name": string;
        /**
          * The icon size
         */
        "size": string;
    }
    interface MyIconSad {
        "size": string;
    }
    interface MyIconSadSvg {
        "size": string;
    }
    interface MyIconSmile {
        "size": string;
    }
    interface MyIconSmileSvg {
        "size": string;
    }
}
declare global {
    interface HTMLMyIcon1Element extends Components.MyIcon1, HTMLStencilElement {
    }
    var HTMLMyIcon1Element: {
        prototype: HTMLMyIcon1Element;
        new (): HTMLMyIcon1Element;
    };
    interface HTMLMyIcon2Element extends Components.MyIcon2, HTMLStencilElement {
    }
    var HTMLMyIcon2Element: {
        prototype: HTMLMyIcon2Element;
        new (): HTMLMyIcon2Element;
    };
    interface HTMLMyIcon3Element extends Components.MyIcon3, HTMLStencilElement {
    }
    var HTMLMyIcon3Element: {
        prototype: HTMLMyIcon3Element;
        new (): HTMLMyIcon3Element;
    };
    interface HTMLMyIconSadElement extends Components.MyIconSad, HTMLStencilElement {
    }
    var HTMLMyIconSadElement: {
        prototype: HTMLMyIconSadElement;
        new (): HTMLMyIconSadElement;
    };
    interface HTMLMyIconSadSvgElement extends Components.MyIconSadSvg, HTMLStencilElement {
    }
    var HTMLMyIconSadSvgElement: {
        prototype: HTMLMyIconSadSvgElement;
        new (): HTMLMyIconSadSvgElement;
    };
    interface HTMLMyIconSmileElement extends Components.MyIconSmile, HTMLStencilElement {
    }
    var HTMLMyIconSmileElement: {
        prototype: HTMLMyIconSmileElement;
        new (): HTMLMyIconSmileElement;
    };
    interface HTMLMyIconSmileSvgElement extends Components.MyIconSmileSvg, HTMLStencilElement {
    }
    var HTMLMyIconSmileSvgElement: {
        prototype: HTMLMyIconSmileSvgElement;
        new (): HTMLMyIconSmileSvgElement;
    };
    interface HTMLElementTagNameMap {
        "my-icon-1": HTMLMyIcon1Element;
        "my-icon-2": HTMLMyIcon2Element;
        "my-icon-3": HTMLMyIcon3Element;
        "my-icon-sad": HTMLMyIconSadElement;
        "my-icon-sad-svg": HTMLMyIconSadSvgElement;
        "my-icon-smile": HTMLMyIconSmileElement;
        "my-icon-smile-svg": HTMLMyIconSmileSvgElement;
    }
}
declare namespace LocalJSX {
    interface MyIcon1 {
        /**
          * The icon name
         */
        "name"?: string;
        /**
          * The icon size
         */
        "size"?: string;
    }
    interface MyIcon2 {
        /**
          * The icon name
         */
        "name"?: string;
        /**
          * The icon size
         */
        "size"?: string;
    }
    interface MyIcon3 {
        /**
          * The icon name
         */
        "name"?: string;
        /**
          * The icon size
         */
        "size"?: string;
    }
    interface MyIconSad {
        "size"?: string;
    }
    interface MyIconSadSvg {
        "size"?: string;
    }
    interface MyIconSmile {
        "size"?: string;
    }
    interface MyIconSmileSvg {
        "size"?: string;
    }
    interface IntrinsicElements {
        "my-icon-1": MyIcon1;
        "my-icon-2": MyIcon2;
        "my-icon-3": MyIcon3;
        "my-icon-sad": MyIconSad;
        "my-icon-sad-svg": MyIconSadSvg;
        "my-icon-smile": MyIconSmile;
        "my-icon-smile-svg": MyIconSmileSvg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-icon-1": LocalJSX.MyIcon1 & JSXBase.HTMLAttributes<HTMLMyIcon1Element>;
            "my-icon-2": LocalJSX.MyIcon2 & JSXBase.HTMLAttributes<HTMLMyIcon2Element>;
            "my-icon-3": LocalJSX.MyIcon3 & JSXBase.HTMLAttributes<HTMLMyIcon3Element>;
            "my-icon-sad": LocalJSX.MyIconSad & JSXBase.HTMLAttributes<HTMLMyIconSadElement>;
            "my-icon-sad-svg": LocalJSX.MyIconSadSvg & JSXBase.HTMLAttributes<HTMLMyIconSadSvgElement>;
            "my-icon-smile": LocalJSX.MyIconSmile & JSXBase.HTMLAttributes<HTMLMyIconSmileElement>;
            "my-icon-smile-svg": LocalJSX.MyIconSmileSvg & JSXBase.HTMLAttributes<HTMLMyIconSmileSvgElement>;
        }
    }
}
